### ISSUE TITLE
Recent Files

### ISSUE THREAD

**Issue by ReiMartins** [tajmone/Tonton-Pixel-Photoshop-Scripts#1]
Hi, 
I want to know if you have "List Recent Files” is a miscellaneous utility script using the JSON Action Manager.
I dont know why but I have some problems to access your blog.
I´m building some extension to Photoshop and your blog is helping me a lot.
Thanks.

**Comment by tajmone** [comment]
Hi @ReiMartins! Sorry for the delay in my reply. I am a bit confused about the "my blog" issue. Maybe you are referring to Tonton Pixel’s Blog (www.tonton-pixel.com), from which I have downloaded the scripts that I have put in this repository, which is a blog by Michel MARIANI.
I too experience problem accessing it (timeout error), and it has been so for over a year, and the only way I can access it is via Wayback Machine. This is the reason why I have gathered all of Mariani's scripts and utilities in this repository, so they can be accessible again—I've tried to contact the author but failed, the only means would be via the contact form of the blog, which isn't accessible.
As for the "List Recent Files” script, no, I don't have it. Please keep in mind that I have shared these scripts here but I don't actually use them: my interest was in the Photoshop shapes files format, so I download Mariani's scripts to study PS shapes for a project which is not related to JavaScript. Also, I don't have a Mac, and it seems that many of these scripts are Mac-related.
When I realized that there is little material available on Photoshop file formats, especially on custom shapes, I though it would be a good idea to share my findings on GitHub (it was a long research, mostly fruitless, except for these scripts and documents of Mariani).
So, at present this repository is intended only as an archive copy of Mariani's excellent work. But if you think that "List Recent Files" and other scripts might enrich this collection with further functionality, I could add a folder for extra scripts to integrate in this collection—but I'd rather keep separate Mariani's work from 3rd party contributions.
As for the Tonton scripts in general, if you have been using them I'd really appreciate some feedback. I think this repository would do with some documentation contributed by people who work with them. If this is your case, I'll be happy to add you to the project so you can expand on it.
I am not sure if I managed to reply (though lately) to your question.

**Comment by ReiMartins** [comment]
Thanks for reply.
Sorry, I think that blog was yours. ;)
I have the same problem to access "the Blog"...(timeout error).
I have a extension to Photoshop and want to upgrade same function...
How I´m learning about javascript this scripts help me to understand develope process.

Thanks!

**Comment by tajmone** [comment]
You're welcome @ReiMartins!
I'll be closing this issue in a day or two then. If you have any suggestions, links, examples, ecc., feel free to drop them here as issues at any time.
Keep in mind that on Tonton blog there are quite a lot of examples on how to use these scripts. But since the examples didn't specify a license, I didn't include them in this repo.
In the root/README file of the repo you'll find a link to the cached copy of Tonton on Wayback Machine, its worth a visit (and you can view most of the blog).
